/*
 * This source file was generated by the Gradle 'init' task
 */
package inventario;

import inventario.model.Producto;

public class App {

    public static void main(String[] args) {
        System.out.println("Sistema de Inventario");
        
        Producto producto1 = new Producto("Laptop", 1500.00, 10, "LP1001");
        Producto producto2 = new Producto("Smartphone", 800.00, 25, "SP2002");
        

        producto1.mostrarProducto();
        producto2.mostrarProducto();

        
    }

}



